project:
  type: website

website:
  title: "Data Analysis Challenge"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/akins11/
      - icon: twitter
        href: https://twitter.com/Akinwande_ay24?s=09
format:
  html:
    theme: 
      light: litera
      dark: superhero
    css: styles.css



